// Generated by CoffeeScript 1.6.2
module.exports = function(app, passport, auth) {
  var articles, users, vendors;

  users = require('../app/controllers/users');
  app.get('/login', users.login);
  app.post('/login', passport.authenticate('local', {
    failureRedirect: '/login',
    failureFlash: true
  }), function(req, res) {
    res.redirect('/');
  });
  app.get('/logout', users.logout);
  app.get('/users', users.index);
  app.get('/users/new', users["new"]);
  app.post('/users', users.create);
  app.get('/users/:userId/edit', auth.requiresLogin, users.edit);
  app.put('/users/:userId', auth.requiresLogin, users.update);
  app.get('/users/:userId/destroy', auth.requiresLogin, users.destroy);
  app.param('userId', users.user);
  articles = require('../app/controllers/articles');
  app.get('/', articles.index);
  app.get('/articles', articles.manage);
  app.get('/articles/new', auth.requiresLogin, articles["new"]);
  app.get('/articles/:articleId', articles.show);
  app.post('/articles', auth.requiresLogin, articles.create);
  app.get('/articles/:articleId/edit', auth.requiresLogin, articles.edit);
  app.put('/articles/:articleId', auth.requiresLogin, articles.update);
  app.get('/articles/:articleId/destroy', auth.requiresLogin, articles.destroy);
  app.param('articleId', articles.article);
  vendors = require('../app/controllers/vendors');
  app.get('/vendor-index', vendors.index);
  app.get('/vendor/json', vendors.json);
  app.post('/vendors', vendors.create);
  app.get('/vendors', vendors.manage);
  app.get('/vendors/new', vendors["new"]);
  app.get('/vendors/:vendorId', vendors.show);
  app.get('/vendors/:vendorId/edit', vendors.edit);
  app.put('/vendors/:vendorId', vendors.update);
  app.get('/vendors/:vendorId/destroy', vendors.destroy);
  app.param('vendorId', vendors.vendor);
};
